In [11]:
import torch
import torch.nn as nn
from torch import einsum
import torch.nn.functional as F
import math


In [ ]:
# Let's get real! Now we know attention, which is of course "all you need" ;) We will 
# implement encoder properly with in pytorch
# we use einops to simplify matrix handling syntax among other things, to install, uncomment:
# !pip3 install einops

In [2]:
print(torch.__version__) # einsum in early versions can be too slow

1.3.0


In [6]:
'''
BLOCK:
batch of tensors of embedding dim n -> self attention + id
-> layer norm -> MLP for each in batch (just plain default) + id
-> layer norm
'''
sentence_len = 9 # batch size
emb_dim = 10 
num_heads = 3
input_batch = torch.rand(sentence_len, emb_dim)
input_batch

tensor([[1.1204e-01, 3.3179e-01, 3.7844e-01, 7.2353e-01, 4.4927e-01, 1.1372e-01,
         2.7527e-01, 2.0844e-01, 3.0714e-01, 1.5609e-01],
        [4.5294e-01, 9.9741e-01, 3.5441e-01, 2.1147e-01, 1.8738e-01, 7.6277e-01,
         5.6122e-01, 9.7209e-04, 2.1788e-01, 8.6360e-01],
        [3.4282e-01, 6.3288e-01, 5.9995e-01, 5.8601e-01, 7.1222e-02, 5.2544e-01,
         3.2955e-01, 2.8433e-01, 3.7653e-01, 6.3157e-01],
        [8.2733e-01, 4.8969e-01, 4.8225e-01, 1.3652e-02, 5.5434e-01, 2.6493e-01,
         2.8982e-01, 6.8646e-01, 1.6388e-01, 4.6974e-01],
        [5.5633e-01, 5.6522e-01, 9.8118e-01, 4.0900e-01, 2.4492e-01, 1.8387e-01,
         2.1073e-01, 7.3774e-01, 1.6522e-01, 6.4002e-01],
        [5.3758e-01, 8.9740e-01, 8.6875e-01, 8.8043e-01, 1.6907e-01, 3.2457e-01,
         7.3095e-01, 7.8696e-01, 7.5072e-01, 4.4058e-01],
        [9.2194e-01, 4.5239e-01, 8.8996e-01, 9.5824e-01, 6.2432e-01, 6.7026e-01,
         7.6904e-01, 5.4834e-01, 5.6674e-01, 9.1058e-01],
        [8.5816e-01, 5.0199

In [19]:
def attention(Q, K, V):
    ''' Functional implementation for scaled dot product attention formula'''
    dot_prod = torch.matmul(Q, torch.transpose(K, -2, -1)) #swap last 2 dims, regardless of batch dim
    K_dim = K.size(-1)
    softmax = F.softmax(dot_prod/math.sqrt(K_dim), dim = -1)
    attention = torch.matmul(softmax, V)
    return attention

class SelfAttentionWide(nn.Module):
    def __init__(self, emb_dim, num_heads):
        super().__init__()
        # we want to output the same dim as embedding to enable residual connection
        # init 3 matrices all the same
        self.M_Q, self.M_V, self.M_K = \
            [nn.Linear(emb_dim, emb_dim*num_heads, bias=False) for _ in range(3)]
        
        self.M_merge_heads = nn.Linear(emb_dim*num_heads, emb_dim, bias=False)
        
    def forward(self, x):
        # get Q, K, V
        Q = self.M_Q(x)
        K = self.M_K(x)
        V = self.M_V(x)
        multi_att = attention(Q, K, V)
        return self.M_merge_heads(multi_att)
        

In [12]:
attention_layer = SelfAttentionWide(emb_dim, num_heads)
x = attention_layer(input_batch)

In [13]:
x

tensor([[-0.0544,  0.1883, -0.0467, -0.3533,  0.0380, -0.1548, -0.0787, -0.2424,
          0.0815, -0.0482],
        [-0.0539,  0.1869, -0.0471, -0.3514,  0.0367, -0.1543, -0.0785, -0.2426,
          0.0806, -0.0478],
        [-0.0539,  0.1880, -0.0472, -0.3528,  0.0371, -0.1549, -0.0784, -0.2432,
          0.0812, -0.0480],
        [-0.0536,  0.1882, -0.0479, -0.3532,  0.0360, -0.1555, -0.0780, -0.2444,
          0.0817, -0.0481],
        [-0.0527,  0.1890, -0.0477, -0.3537,  0.0364, -0.1552, -0.0781, -0.2444,
          0.0816, -0.0481],
        [-0.0533,  0.1897, -0.0476, -0.3542,  0.0377, -0.1554, -0.0786, -0.2441,
          0.0811, -0.0480],
        [-0.0536,  0.1890, -0.0465, -0.3529,  0.0385, -0.1545, -0.0791, -0.2424,
          0.0806, -0.0479],
        [-0.0542,  0.1894, -0.0477, -0.3542,  0.0375, -0.1558, -0.0786, -0.2441,
          0.0812, -0.0480],
        [-0.0542,  0.1886, -0.0484, -0.3538,  0.0359, -0.1564, -0.0779, -0.2453,
          0.0816, -0.0481]], grad_fn=<MmBackwar

In [14]:
layernorm = nn.LayerNorm(emb_dim)
layernorm(x)

tensor([[ 0.0855,  1.7223,  0.1377, -1.9306,  0.7086, -0.5916, -0.0786, -1.1822,
          1.0019,  0.1272],
        [ 0.0901,  1.7223,  0.1362, -1.9274,  0.7040, -0.5913, -0.0768, -1.1898,
          1.0018,  0.1309],
        [ 0.0898,  1.7229,  0.1351, -1.9279,  0.7041, -0.5921, -0.0754, -1.1880,
          1.0019,  0.1297],
        [ 0.0937,  1.7229,  0.1322, -1.9259,  0.6974, -0.5932, -0.0707, -1.1921,
          1.0052,  0.1305],
        [ 0.0983,  1.7243,  0.1314, -1.9269,  0.6976, -0.5918, -0.0726, -1.1915,
          1.0019,  0.1293],
        [ 0.0940,  1.7264,  0.1322, -1.9272,  0.7049, -0.5923, -0.0763, -1.1878,
          0.9967,  0.1295],
        [ 0.0896,  1.7257,  0.1373, -1.9292,  0.7111, -0.5911, -0.0824, -1.1836,
          0.9947,  0.1279],
        [ 0.0891,  1.7257,  0.1325, -1.9267,  0.7054, -0.5937, -0.0748, -1.1870,
          0.9989,  0.1305],
        [ 0.0913,  1.7243,  0.1304, -1.9233,  0.6976, -0.5956, -0.0681, -1.1936,
          1.0047,  0.1325]], grad_fn=<NativeLay

In [20]:
class Encoder(nn.Module):
    def __init__(self, emb_dim, num_heads):
        super().__init__()
        self.attention_layer = SelfAttentionWide(emb_dim, num_heads)
        self.layernorm1 = nn.LayerNorm(emb_dim)
        self.layernorm2 = nn.LayerNorm(emb_dim)
        # this can be pretty much any mlp we want
        self.mlp = nn.Sequential(nn.Linear(emb_dim, emb_dim), nn.ReLU())
        
    def forward(self, x):
        x = x + self.attention_layer(x)
        x = self.layernorm1(x)
        x = x + self.mlp(x)
        return self.layernorm2(x)

In [21]:
encoder = Encoder(emb_dim, num_heads)
encoder(input_batch)

tensor([[ 0.4111, -0.0066, -0.7764,  2.4596,  0.1680, -0.9193,  0.5762, -1.2372,
         -0.0104, -0.6651],
        [ 0.5130,  1.1780, -0.8943,  0.0585, -1.5254,  0.6492,  0.5785, -0.9708,
         -1.1039,  1.5172],
        [ 0.7809,  0.5514, -0.3827,  1.1516, -2.4058,  0.3540,  0.0678, -0.7195,
         -0.4047,  1.0070],
        [ 2.3102, -0.3077, -0.8528, -0.5073, -0.2442, -0.8339,  0.1017,  1.0187,
         -1.2215,  0.5369],
        [ 1.6129,  0.0167,  0.9968, -0.1645, -1.3619, -1.1696, -0.3388,  0.9259,
         -1.2709,  0.7534],
        [ 0.9896,  1.1583, -0.1301,  0.8942, -2.2386, -0.8275,  0.6987, -0.0103,
          0.2503, -0.7846],
        [ 1.4344, -1.3777, -0.4036,  1.5942, -0.9197, -0.3560,  0.6686, -0.7516,
         -0.7658,  0.8770],
        [ 1.0196, -0.5523, -0.9151,  1.5884, -1.0625,  0.6596,  0.8792,  0.6222,
         -0.9409, -1.2982],
        [ 0.6927, -0.3736, -1.5784, -0.8611, -1.2976,  0.7043, -0.4600,  1.1697,
          0.5664,  1.4377]], grad_fn=<NativeLay